CREATE TABLE IF NOT EXISTS public.rbx_t_card_validation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    card_number character varying(16) COLLATE pg_catalog."default" NOT NULL,
    attempts integer NOT NULL DEFAULT 0,
    updated_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT rbx_t_card_validation_pkey PRIMARY KEY (id),
    CONSTRAINT uq_card_validation_card_number UNIQUE (card_number)
);

-- Create index for faster lookups by card number
CREATE INDEX IF NOT EXISTS idx_rbx_t_card_validation_card_number ON public.rbx_t_card_validation (card_number);

-- Create index for faster lookups by updated_at
CREATE INDEX IF NOT EXISTS idx_rbx_t_card_validation_updated_at ON public.rbx_t_card_validation (updated_at);
