
mock:
  enabled: true

spring:
  application:
    name: forgot-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://34.18.104.74:5432/dukhanbank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Poclab_123#
    hikari:
      max-lifetime: 540000
  main:
    allow-bean-definition-overriding: true

server:
  port: 9090