////
//// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
//// See https://eclipse-ee4j.github.io/jaxb-ri
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2025.09.30 at 08:02:36 PM IST
////
//
//
//package com.dukhan.forgot.infrastructure.common.xmlResponse;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * <p>Java class for EaiBodyType complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="EaiBodyType"&gt;
// *   &lt;complexContent&gt;
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
// *       &lt;choice&gt;
// *         &lt;element name="eAI_REQUEST" type="{urn:esbbank.com/gbo/xml/schemas/v1_0/}EaiRequestType"/&gt;
// *         &lt;element name="eAI_REPLY" type="{urn:esbbank.com/gbo/xml/schemas/v1_0/}EaiReplyType"/&gt;
// *       &lt;/choice&gt;
// *     &lt;/restriction&gt;
// *   &lt;/complexContent&gt;
// * &lt;/complexType&gt;
// * </pre>
// *
// *
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "EaiBodyType", propOrder = {
//    "eairequest",
//    "eaireply"
//})
//public class EaiBodyType {
//
//    @XmlElement(name = "eAI_REQUEST", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
//    protected EaiRequestType eairequest;
//    @XmlElement(name = "eAI_REPLY", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
//    protected EaiReplyType eaireply;
//
//    /**
//     * Gets the value of the eairequest property.
//     *
//     * @return
//     *     possible object is
//     *     {@link EaiRequestType }
//     *
//     */
//    public EaiRequestType getEAIREQUEST() {
//        return eairequest;
//    }
//
//    /**
//     * Sets the value of the eairequest property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link EaiRequestType }
//     *
//     */
//    public void setEAIREQUEST(EaiRequestType value) {
//        this.eairequest = value;
//    }
//
//    /**
//     * Gets the value of the eaireply property.
//     *
//     * @return
//     *     possible object is
//     *     {@link EaiReplyType }
//     *
//     */
//    public EaiReplyType getEAIREPLY() {
//        return eaireply;
//    }
//
//    /**
//     * Sets the value of the eaireply property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link EaiReplyType }
//     *
//     */
//    public void setEAIREPLY(EaiReplyType value) {
//        this.eaireply = value;
//    }
//
//}
