////
//// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
//// See https://eclipse-ee4j.github.io/jaxb-ri
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2025.09.30 at 08:02:36 PM IST
////
//
//
//package com.dukhan.forgot.infrastructure.common.xmlResponse;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * <p>Java class for EaiHeaderType complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="EaiHeaderType"&gt;
// *   &lt;complexContent&gt;
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
// *       &lt;sequence&gt;
// *         &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
// *         &lt;element name="serviceType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
// *         &lt;element name="serviceVersion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
// *         &lt;element name="client" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
// *         &lt;element name="clientChannel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
// *         &lt;element name="msgChannel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
// *         &lt;element name="requestorLanguage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
// *         &lt;element name="securityInfo" type="{urn:esbbank.com/gbo/xml/schemas/v1_0/}SecurityInfoType"/&gt;
// *         &lt;element name="returnCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
// *       &lt;/sequence&gt;
// *     &lt;/restriction&gt;
// *   &lt;/complexContent&gt;
// * &lt;/complexType&gt;
// * </pre>
// *
// *
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "EaiHeaderType", propOrder = {
//    "serviceName",
//    "serviceType",
//    "serviceVersion",
//    "client",
//    "clientChannel",
//    "msgChannel",
//    "requestorLanguage",
//    "securityInfo",
//    "returnCode"
//})
//public class EaiHeaderType {
//
//    @XmlElement(name = "serviceName", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected String serviceName;
//    @XmlElement(name = "serviceType", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected String serviceType;
//    @XmlElement(name = "serviceVersion", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected String serviceVersion;
//    @XmlElement(name = "client", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected String client;
//    @XmlElement(name = "clientChannel", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected String clientChannel;
//    @XmlElement(name = "msgChannel", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected String msgChannel;
//    @XmlElement(name = "requestorLanguage", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected String requestorLanguage;
//    @XmlElement(name = "securityInfo", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected SecurityInfoType securityInfo;
//    @XmlElement(name = "returnCode", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected String returnCode;
//
//    /**
//     * Gets the value of the serviceName property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getServiceName() {
//        return serviceName;
//    }
//
//    /**
//     * Sets the value of the serviceName property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setServiceName(String value) {
//        this.serviceName = value;
//    }
//
//    /**
//     * Gets the value of the serviceType property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getServiceType() {
//        return serviceType;
//    }
//
//    /**
//     * Sets the value of the serviceType property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setServiceType(String value) {
//        this.serviceType = value;
//    }
//
//    /**
//     * Gets the value of the serviceVersion property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getServiceVersion() {
//        return serviceVersion;
//    }
//
//    /**
//     * Sets the value of the serviceVersion property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setServiceVersion(String value) {
//        this.serviceVersion = value;
//    }
//
//    /**
//     * Gets the value of the client property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getClient() {
//        return client;
//    }
//
//    /**
//     * Sets the value of the client property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setClient(String value) {
//        this.client = value;
//    }
//
//    /**
//     * Gets the value of the clientChannel property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getClientChannel() {
//        return clientChannel;
//    }
//
//    /**
//     * Sets the value of the clientChannel property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setClientChannel(String value) {
//        this.clientChannel = value;
//    }
//
//    /**
//     * Gets the value of the msgChannel property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getMsgChannel() {
//        return msgChannel;
//    }
//
//    /**
//     * Sets the value of the msgChannel property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setMsgChannel(String value) {
//        this.msgChannel = value;
//    }
//
//    /**
//     * Gets the value of the requestorLanguage property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getRequestorLanguage() {
//        return requestorLanguage;
//    }
//
//    /**
//     * Sets the value of the requestorLanguage property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setRequestorLanguage(String value) {
//        this.requestorLanguage = value;
//    }
//
//    /**
//     * Gets the value of the securityInfo property.
//     *
//     * @return
//     *     possible object is
//     *     {@link SecurityInfoType }
//     *
//     */
//    public SecurityInfoType getSecurityInfo() {
//        return securityInfo;
//    }
//
//    /**
//     * Sets the value of the securityInfo property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link SecurityInfoType }
//     *
//     */
//    public void setSecurityInfo(SecurityInfoType value) {
//        this.securityInfo = value;
//    }
//
//    /**
//     * Gets the value of the returnCode property.
//     *
//     * @return
//     *     possible object is
//     *     {@link String }
//     *
//     */
//    public String getReturnCode() {
//        return returnCode;
//    }
//
//    /**
//     * Sets the value of the returnCode property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *
//     */
//    public void setReturnCode(String value) {
//        this.returnCode = value;
//    }
//
//}
