////
//// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
//// See https://eclipse-ee4j.github.io/jaxb-ri
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2025.09.30 at 08:02:36 PM IST
////
//
//
//package com.dukhan.forgot.infrastructure.common.xmlResponse;
//
//import javax.xml.bind.annotation.*;
//
//
///**
// * <p>Java class for EaiMessageType complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="EaiMessageType"&gt;
// *   &lt;complexContent&gt;
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
// *       &lt;sequence&gt;
// *         &lt;element name="eAI_HEADER" type="{urn:esbbank.com/gbo/xml/schemas/v1_0/}EaiHeaderType"/&gt;
// *         &lt;element name="eAI_BODY" type="{urn:esbbank.com/gbo/xml/schemas/v1_0/}EaiBodyType"/&gt;
// *       &lt;/sequence&gt;
// *     &lt;/restriction&gt;
// *   &lt;/complexContent&gt;
// * &lt;/complexType&gt;
// * </pre>
// *
// *
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "EaiMessageType", propOrder = {
//    "eaiheader",
//    "eaibody"
//})
//@XmlRootElement(name = "eAI_MESSAGE", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
//public class EaiMessageType {
//
//    @XmlElement(name = "eAI_HEADER", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected EaiHeaderType eaiheader;
//    @XmlElement(name = "eAI_BODY", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", required = true)
//    protected EaiBodyType eaibody;
//
//    /**
//     * Gets the value of the eaiheader property.
//     *
//     * @return
//     *     possible object is
//     *     {@link EaiHeaderType }
//     *
//     */
//    public EaiHeaderType getEAIHEADER() {
//        return eaiheader;
//    }
//
//    /**
//     * Sets the value of the eaiheader property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link EaiHeaderType }
//     *
//     */
//    public void setEAIHEADER(EaiHeaderType value) {
//        this.eaiheader = value;
//    }
//
//    /**
//     * Gets the value of the eaibody property.
//     *
//     * @return
//     *     possible object is
//     *     {@link EaiBodyType }
//     *
//     */
//    public EaiBodyType getEAIBODY() {
//        return eaibody;
//    }
//
//    /**
//     * Sets the value of the eaibody property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link EaiBodyType }
//     *
//     */
//    public void setEAIBODY(EaiBodyType value) {
//        this.eaibody = value;
//    }
//
//}
