////
//// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
//// See https://eclipse-ee4j.github.io/jaxb-ri
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2025.09.30 at 08:02:36 PM IST
////
//
//
//package com.dukhan.forgot.infrastructure.common.xmlResponse;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * <p>Java class for EaiRequestType complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType name="EaiRequestType"&gt;
// *   &lt;complexContent&gt;
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
// *       &lt;sequence&gt;
// *         &lt;element name="sendSMSRequest" type="{urn:esbbank.com/gbo/xml/schemas/v1_0/}SendSMSRequest"/&gt;
// *       &lt;/sequence&gt;
// *     &lt;/restriction&gt;
// *   &lt;/complexContent&gt;
// * &lt;/complexType&gt;
// * </pre>
// *
// *
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "EaiRequestType", propOrder = {
//    "sendSMSRequest",
//    "crmCreateTicketRequest"
//})
//public class EaiRequestType {
//
//    @XmlElement(name = "sendSMSRequest", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
//    protected SendSMSRequest sendSMSRequest;
//    @XmlElement(name = "crmCreateTicketRequest", namespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
//    protected CrmCreateTicketRequest crmCreateTicketRequest;
//
//    /**
//     * Gets the value of the sendSMSRequest property.
//     *
//     * @return
//     *     possible object is
//     *     {@link SendSMSRequest }
//     *
//     */
//    public SendSMSRequest getSendSMSRequest() {
//        return sendSMSRequest;
//    }
//
//    /**
//     * Sets the value of the sendSMSRequest property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link SendSMSRequest }
//     *
//     */
//    public void setSendSMSRequest(SendSMSRequest value) {
//        this.sendSMSRequest = value;
//    }
//
//    /**
//     * Gets the value of the crmCreateTicketRequest property.
//     *
//     * @return
//     *     possible object is
//     *     {@link CrmCreateTicketRequest }
//     *
//     */
//    public CrmCreateTicketRequest getCrmCreateTicketRequest() {
//        return crmCreateTicketRequest;
//    }
//
//    /**
//     * Sets the value of the crmCreateTicketRequest property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link CrmCreateTicketRequest }
//     *
//     */
//    public void setCrmCreateTicketRequest(CrmCreateTicketRequest value) {
//        this.crmCreateTicketRequest = value;
//    }
//
//}
