package com.dukhan.forgot.adapter.api.service.impl;

import com.dukhan.forgot.adapter.api.service.XmlGeneratorService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.test.util.ReflectionTestUtils;
import java.util.HashMap;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;

class XmlGeneratorServiceTest {

    @InjectMocks
    private XmlGeneratorService xmlGeneratorService;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);

        // Inject mock @Value fields
        ReflectionTestUtils.setField(xmlGeneratorService, "userId", "testUser");
        ReflectionTestUtils.setField(xmlGeneratorService, "password", "testPass");
    }

    @Test
    void testGenerateDcardPinVerificationXml_Success() throws Exception {
        // Arrange
        Map<String, Object> headers = new HashMap<>();
        headers.put("serviceName", "DCARD.PIN.VERIFICATION");
        headers.put("serviceType", "SYNC");
        headers.put("serviceVersion", "1");
        headers.put("client", "BKR");
        headers.put("clientChannel", "MOB");
        headers.put("msgChannel", "MQ");
        headers.put("requestorLanguage", "E");

        Map<String, Object> payload = new HashMap<>();
        payload.put("cardNumber", "1234567890123456");
        payload.put("requestTime", "20251007123000000");
        payload.put("referenceNum", "TAM12345");

        // Act
        String xmlResult = xmlGeneratorService.generateDcardPinVerificationXml(headers, payload);

        // Assert
        assertNotNull(xmlResult);
        assertTrue(xmlResult.contains("<NS1:eAI_MESSAGE"));
        assertTrue(xmlResult.contains("<NS1:eAI_HEADER>"));
        assertTrue(xmlResult.contains("<NS1:eAI_BODY>"));
        assertTrue(xmlResult.contains("<NS1:debitCardPINVerificationRequest>"));
        assertTrue(xmlResult.contains("1234567890123456"));
        assertTrue(xmlResult.contains("testUser"));
        assertTrue(xmlResult.contains("testPass"));
    }

    @Test
    void testGenerateDcardPinVerificationXml_EmptyPayload_StillGeneratesValidXml() throws Exception {
        // Arrange
        Map<String, Object> headers = new HashMap<>();
        Map<String, Object> payload = new HashMap<>();

        // Act
        String xml = xmlGeneratorService.generateDcardPinVerificationXml(headers, payload);

        // Assert
        assertNotNull(xml);
        assertTrue(xml.contains("<NS1:eAI_MESSAGE"));
        assertTrue(xml.contains("DCARD.PIN.VERIFICATION"));
        assertTrue(xml.contains("SYNC"));
        assertTrue(xml.contains("<NS1:debitCardPINVerificationRequest"));
    }

    @Test
    void testGenerateDcardPinVerificationXml_MissingRequestTimeAndReferenceNum_AutoGenerated() throws Exception {
        // Arrange
        Map<String, Object> headers = Map.of("client", "WEB");
        Map<String, Object> payload = new HashMap<>();
        payload.put("cardNumber", "9999888877776666");
        payload.put("requestTime", "");
        payload.put("referenceNum", null);

        // Act
        String xml = xmlGeneratorService.generateDcardPinVerificationXml(headers, payload);

        // Assert
        assertNotNull(xml);
        assertTrue(xml.contains("9999888877776666"));
        assertTrue(xml.contains("requestTime")); // auto-generated timestamp
        assertTrue(xml.contains("referenceNum")); // auto-generated reference number
    }

    @Test
    void testGenerateDcardPinVerificationXml_NullHeadersAndPayload_StillGeneratesDefaultXml() throws Exception {
        // Arrange
        Map<String, Object> headers = null;
        Map<String, Object> payload = null;

        // Act
        String xml = xmlGeneratorService.generateDcardPinVerificationXml(headers, payload);

        // Assert
        assertNotNull(xml);
        assertTrue(xml.contains("<NS1:eAI_MESSAGE"));
        assertTrue(xml.contains("DCARD.PIN.VERIFICATION")); // default header
        assertTrue(xml.contains("<NS1:eAI_BODY>"));
    }

    @Test
    void testGeneratedXml_HasCorrectNamespacesAndElements() throws Exception {
        // Arrange
        Map<String, Object> headers = Map.of("serviceName", "DCARD.PIN.VERIFICATION");
        Map<String, Object> payload = Map.of("cardNumber", "1111222233334444");

        // Act
        String xml = xmlGeneratorService.generateDcardPinVerificationXml(headers, payload);

        // Assert
        assertTrue(xml.contains("xmlns:NS1=\"urn:esbbank.com/gbo/xml/schemas/v1_0/\""));
        assertTrue(xml.contains("xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""));
        assertTrue(xml.contains("<NS1:securityInfo>"));
        assertTrue(xml.contains("<NS1:authentication>"));
        assertTrue(xml.contains("<NS1:authorization>"));
        assertTrue(xml.contains("<NS1:UserId>testUser</NS1:UserId>"));
        assertTrue(xml.contains("<NS1:Password>testPass</NS1:Password>"));
    }
}
